### ISSUE TITLE
ability to load policies over OCI

### ISSUE THREAD

**Issue by developer-guy** [nsmith5/rekor-sidekick#34]
Rego policies can be shared over OCI registries by using the conftest tool which means that you can basically push and pull your Rego policies. So, we can load policies over OCI registries also.

👉 https://www.conftest.dev/sharing/

**Comment by nsmith5** [comment]
I think this and the directory for policies is generally a good idea but I'd like to spec out what the config would look like before developing as I think it needs a change. Perhaps something like:

```YAML
policies:
  inline:
  - name: foo
    description: bar
    policy: |
        package sidekick
        default alert = true
  directories:
  - /etc/rekor-sidekick/policies.d/
  oci-registry:
  - # Not sure on schema here?
```
